import type { Metadata } from "next";
import "./globals.css";
import  ThemeProvider  from "@/providers/theme-provider";
import  Toaster  from "@/components/ui/toaster";
import { dana } from "./styles/fonts";
import ReactQueryProvider from "@/providers/reactquery-provider";

export const metadata: Metadata = {
  title: "Dimshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={dana.className}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <main>{children}</main>
            <Toaster />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
