import { AuthProvider } from "@/components/AuthProvider";
import FullMenu from "@/components/header/FullMenu";
import BodyPrvider from "@/components/ui-providers/BodyProvider";
import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Dimshop - userpanel",
  description: "Generated by create next app",
};

export default function UserLayouLayout({
  children,
  userinfo,
  address,
  orders,
}: Readonly<{
  children: React.ReactNode;
  userinfo: React.ReactNode;
  address: React.ReactNode;
  orders: React.ReactNode;
}>) {
  const cookie: string | null = cookies().get("authToken")?.value ?? null;
  return (
    <>
      <FullMenu />
      <BodyPrvider>
        <AuthProvider initialToken={cookie}>
          <div className="">{children}</div>
          {/* more commponents */}
          <div className="flex flex-col lg:flex-row md:gap-x-5">
            <div className="flex-[1] md:flex-[8]">{userinfo}</div>
            <div className="flex-[1] md:flex-[4]">{address}</div>
          </div>
          <div className="">{orders}</div>
          {/* <div className="fixed bottom-0 left-0 w-full z-20">
          <MobileMenu />
        </div> */}
        </AuthProvider>
      </BodyPrvider>
    </>
  );
}
